### ISSUE TITLE
Weird link behavior

### ISSUE THREAD

**Issue by aretecode** [the-grid/ed#258] opened 2016-07-31 23:50 UTC
https://www.dropbox.com/s/rm93mc1j4q63bg2/editor%20confusing.gif?dl=0

Steps to reproduce:

1) Enter a link
2) Press [enter] key

**Comment by forresto** [comment] 2016-08-01 15:38
@aretecode That's by design as far as I can see. Webapp should set status text in the blue bar: "Sharing http://test.com/" and progress of the share.

**Comment by forresto** [comment] 2016-08-01 17:48
@aretecode can I close this as "by design" or can you make a suggestion?

**Closed as completed** 2016-08-12 08:54 UTC
